/* Py30 curriculum — the full 30-day map. `ready: true` days have content files in js/days/. */
window.CURRICULUM = {
  weeks: [
    { n: 1, title: "Week 1 — First steps", ar: "الخطوات الأولى" },
    { n: 2, title: "Week 2 — Loops and collections", ar: "التكرار والمجموعات" },
    { n: 3, title: "Week 3 — Organize like a pro", ar: "التنظيم الاحترافي" },
    { n: 4, title: "Week 4 — Algorithms and AI", ar: "الخوارزميات والذكاء الاصطناعي" },
    { n: 5, title: "Final — Your capstone project", ar: "المشروع الختامي" },
  ],
  days: [
    { d: 1, w: 1, type: "lesson", title: "Hello, Python: print and comments", ready: true },
    { d: 2, w: 1, type: "lesson", title: "Variables and data types", ready: true },
    { d: 3, w: 1, type: "lesson", title: "Input, conversion and math", ready: true },
    { d: 4, w: 1, type: "lesson", title: "Strings and f-strings", ready: true },
    { d: 5, w: 1, type: "lesson", title: "Decisions: if, elif, else", ready: true },
    { d: 6, w: 1, type: "review", title: "Review + project: Smart Calculator", ready: true },
    { d: 7, w: 1, type: "rest", title: "Rest day", ready: true },
    { d: 8, w: 2, type: "lesson", title: "while loops", ready: true },
    { d: 9, w: 2, type: "lesson", title: "for loops and range", ready: true },
    { d: 10, w: 2, type: "lesson", title: "Lists", ready: true },
    { d: 11, w: 2, type: "lesson", title: "Tuples and sets", ready: true },
    { d: 12, w: 2, type: "lesson", title: "Dictionaries", ready: true },
    { d: 13, w: 2, type: "review", title: "Review + project: Guessing game and quiz", ready: true },
    { d: 14, w: 2, type: "rest", title: "Rest day", ready: true },
    { d: 15, w: 3, type: "lesson", title: "Functions", ready: true },
    { d: 16, w: 3, type: "lesson", title: "More functions and modules", ready: true },
    { d: 17, w: 3, type: "lesson", title: "Errors and files", ready: true },
    { d: 18, w: 3, type: "lesson", title: "OOP: classes and objects", ready: true },
    { d: 19, w: 3, type: "lesson", title: "OOP: inheritance", ready: true },
    { d: 20, w: 3, type: "review", title: "Review + project: Grades manager", ready: true },
    { d: 21, w: 3, type: "rest", title: "Rest day", ready: true },
    { d: 22, w: 4, type: "lesson", title: "Problem solving: search and sort", ready: true },
    { d: 23, w: 4, type: "lesson", title: "numpy basics", ready: true },
    { d: 24, w: 4, type: "lesson", title: "Data and machine learning ideas", ready: true },
    { d: 25, w: 4, type: "lesson", title: "Your first model with scikit-learn", ready: true },
    { d: 26, w: 4, type: "lesson", title: "Text classification and a mini chatbot", ready: true },
    { d: 27, w: 4, type: "review", title: "Review + mini AI project", ready: true },
    { d: 28, w: 4, type: "rest", title: "Rest day", ready: true },
    { d: 29, w: 5, type: "project", title: "Capstone: plan and build", ready: true },
    { d: 30, w: 5, type: "project", title: "Capstone: finish, polish, certificate", ready: true },
  ],
};
