/* Py30 glossary: [term, English meaning, Arabic explanation, day] */
window.GLOSSARY = [
  ["program", "A list of instructions the computer follows, in order.", "برنامج: مجموعة تعليمات ينفذها الحاسب بالترتيب.", 1],
  ["code", "The text you write in a programming language.", "الكود: النص الذي نكتبه بلغة البرمجة.", 1],
  ["Python", "A popular, readable programming language used in web, data science and AI.", "بايثون: لغة برمجة سهلة القراءة ومستخدمة بكثرة في الذكاء الاصطناعي والبيانات.", 1],
  ["print()", "A built-in function that shows a value on the screen.", "دالة تعرض القيم على الشاشة.", 1],
  ["function", "A named piece of code that does a job. You call it with parentheses: name().", "دالة: كود له اسم يقوم بمهمة، نستدعيه بالأقواس.", 1],
  ["argument", "A value you give to a function inside the parentheses.", "المُعامل: القيمة التي نرسلها للدالة داخل الأقواس.", 1],
  ["string (str)", "Text. Written between quotes: \"hello\" or 'hello'.", "نص: يُكتب بين علامتي تنصيص.", 1],
  ["comment", "A note for humans, starting with #. Python ignores it.", "تعليق: ملاحظة تبدأ بـ # يتجاهلها بايثون.", 1],
  ["syntax", "The grammar rules of a programming language.", "القواعد: طريقة كتابة الكود الصحيحة.", 1],
  ["error / bug", "A mistake in the code. Finding and fixing it is called debugging.", "خطأ في الكود، وإصلاحه يسمى debugging.", 1],
  ["escape character", "A backslash code inside a string: \\n new line, \\t tab, \\\" a quote.", "رموز خاصة داخل النص مثل \\n لسطر جديد.", 1],
  ["variable", "A name that refers to a value, like a labeled box.", "متغير: اسم يشير إلى قيمة، مثل صندوق عليه ملصق.", 2],
  ["assignment", "Storing a value in a variable with one =.", "الإسناد: تخزين قيمة في متغير بعلامة = واحدة.", 2],
  ["data type", "The kind of a value: int, float, str, bool…", "نوع البيانات: رقم صحيح، عشري، نص، منطقي…", 2],
  ["int", "A whole number: 7, -3, 2026.", "رقم صحيح بدون كسور.", 2],
  ["float", "A number with a decimal point: 3.14, 2.0.", "رقم عشري.", 2],
  ["bool", "A truth value: True or False.", "قيمة منطقية: صح أو خطأ.", 2],
  ["type()", "A function that tells you the type of a value.", "دالة تعرض نوع القيمة.", 2],
  ["snake_case", "The Python naming style: lowercase words joined with _, like total_price.", "طريقة تسمية المتغيرات بكلمات صغيرة بينها _.", 2],
  ["input()", "Reads one line typed by the user. Always returns a string.", "تقرأ سطرًا يكتبه المستخدم وترجعه نصًا دائمًا.", 3],
  ["type conversion", "Changing a value's type: int(\"5\"), float(\"2.5\"), str(10).", "تحويل نوع القيمة.", 3],
  ["operator", "A symbol that does an operation: + - * / // % **.", "عامل: رمز يقوم بعملية.", 3],
  ["floor division //", "Division that drops the decimal part: 7 // 2 is 3.", "القسمة الصحيحة: تحذف الجزء العشري.", 3],
  ["modulo %", "The remainder of a division: 7 % 2 is 1.", "باقي القسمة.", 3],
  ["expression", "A piece of code that produces a value, like 3 * (x + 1).", "تعبير: كود ينتج قيمة.", 3],
  ["index", "The position of a character or item. Starts at 0.", "الفهرس: رقم الموقع ويبدأ من صفر.", 4],
  ["slicing", "Taking a part of a string or list: s[start:stop:step].", "القص: أخذ جزء من النص.", 4],
  ["method", "A function that belongs to a value, called with a dot: name.upper().", "دالة تابعة للقيمة، نستدعيها بنقطة.", 4],
  ["f-string", "A string starting with f where {expressions} are filled in: f\"Hi {name}\".", "نص يبدأ بحرف f ونضع القيم داخل { }.", 4],
  ["immutable", "Cannot be changed in place. Strings are immutable: methods return a new string.", "غير قابل للتعديل: دوال النص ترجع نصًا جديدًا.", 4],
  ["condition", "An expression that is True or False, used by if.", "شرط: تعبير نتيجته صح أو خطأ.", 5],
  ["comparison operators", "== != < > <= >= compare two values and give a bool.", "عوامل المقارنة وتعطي True أو False.", 5],
  ["logical operators", "and, or, not combine conditions.", "العوامل المنطقية لربط الشروط.", 5],
  ["block", "Indented lines that belong together, e.g. the body of an if.", "بلوك: أسطر مزاحة تنتمي لنفس الجملة.", 5],
  ["indentation", "Spaces at the start of a line. In Python they define blocks (use 4 spaces).", "الإزاحة: مسافات بداية السطر ولها معنى في بايثون.", 5],
  ["nested if", "An if inside another if.", "شرط داخل شرط.", 5],
  ["algorithm", "A clear step-by-step plan to solve a problem.", "خوارزمية: خطوات واضحة لحل مشكلة.", 6],
  ["loop", "Code that repeats.", "حلقة: كود يتكرر.", 8],
  ["while loop", "Repeats while a condition is True.", "حلقة تتكرر طالما الشرط صحيح.", 8],
  ["infinite loop", "A loop whose condition never becomes False.", "حلقة لا نهائية لا تتوقف.", 8],
  ["counter / accumulator", "Variables updated each round to count or total something.", "عدّاد ومجمّع: متغيرات تتحدث في كل دورة.", 8],
  ["sentinel", "A special input value that means stop (like 0 or 'end').", "قيمة خاصة تعني التوقف.", 8],
  ["break / continue", "Exit the loop / skip to the next round.", "الخروج من الحلقة / تخطي الدورة الحالية.", 8],
  ["for loop", "Repeats once for each item of a sequence.", "حلقة تمر على كل عنصر.", 9],
  ["range()", "A sequence of numbers: range(start, stop, step), stop not included.", "مدى من الأرقام، والنهاية غير مشمولة.", 9],
  ["nested loop", "A loop inside another loop.", "حلقة داخل حلقة.", 9],
  ["flag", "A bool variable that records whether something happened.", "متغير منطقي يسجل حدوث شيء.", 9],
  ["list", "An ordered, changeable collection: [1, 2, 3].", "قائمة مرتبة قابلة للتعديل.", 10],
  ["mutable", "Can be changed in place (lists, dicts, sets).", "قابل للتعديل.", 10],
  ["append()", "Adds an item to the end of a list.", "تضيف عنصرًا في نهاية القائمة.", 10],
  ["split() / join()", "Cut a string into a list / glue a list into a string.", "تقسيم النص إلى قائمة / دمج القائمة في نص.", 10],
  ["list comprehension", "[expr for x in items if cond] — build a list in one line.", "إنشاء قائمة في سطر واحد.", 10],
  ["tuple", "An ordered collection that cannot change: (3, 7).", "مجموعة مرتبة غير قابلة للتعديل.", 11],
  ["unpacking", "Assigning the items of a sequence to several variables: a, b = t.", "توزيع عناصر المجموعة على متغيرات.", 11],
  ["set", "An unordered collection of unique items.", "مجموعة بلا تكرار وبلا ترتيب.", 11],
  ["union / intersection / difference", "| & - on sets.", "الاتحاد / التقاطع / الفرق.", 11],
  ["dictionary (dict)", "Key–value pairs: {\"name\": \"Sara\"}.", "قاموس: أزواج مفتاح وقيمة.", 12],
  ["key / value", "The lookup name / the data stored under it.", "المفتاح / القيمة المخزنة.", 12],
  ["KeyError", "Error when a key does not exist; use get().", "خطأ عند طلب مفتاح غير موجود.", 12],
  ["hashing", "The technique that makes dict and set lookups fast.", "تقنية تجعل البحث في القاموس سريعًا.", 14],
  ["def", "Keyword that defines a function.", "كلمة تعريف الدالة.", 15],
  ["parameter / argument", "The name in the definition / the value passed in the call.", "المعامل في التعريف / القيمة المرسلة عند الاستدعاء.", 15],
  ["return", "Sends a value back to the caller and ends the function.", "ترجع قيمة وتنهي الدالة.", 15],
  ["None", "The value meaning \"nothing\"; returned by functions without return.", "قيمة تعني لا شيء.", 15],
  ["scope / local variable", "Where a name exists; variables inside a function are local.", "نطاق المتغير؛ متغيرات الدالة محلية.", 15],
  ["docstring", "A string under def that documents the function.", "نص توثيق الدالة.", 15],
  ["module / import", "A file of reusable code / loading it into your program.", "وحدة كود جاهزة / استيرادها.", 16],
  ["lambda", "A tiny unnamed function: lambda x: x * 2.", "دالة صغيرة بدون اسم.", 16],
  ["recursion / base case", "A function calling itself / the case that stops it.", "دالة تستدعي نفسها / حالة التوقف.", 16],
  ["memoization", "Remembering results of previous calls to avoid repeating work.", "حفظ النتائج السابقة لتسريع الحساب.", 16],
  ["exception", "An error raised while the program runs.", "خطأ يحدث أثناء التشغيل.", 17],
  ["try / except / finally", "Run code, handle a specific error, always clean up.", "تجربة الكود ومعالجة الخطأ والتنظيف دائمًا.", 17],
  ["raise", "Create an error on purpose: raise ValueError(\"...\").", "رفع خطأ عمدًا.", 17],
  ["file mode", "\"r\" read, \"w\" write (erase), \"a\" append.", "طريقة فتح الملف: قراءة، كتابة، إضافة.", 17],
  ["CSV", "Comma-separated values: a table stored as text.", "ملف نصي يمثل جدولًا.", 17],
  ["class / object", "A blueprint / an instance built from it.", "القالب / النسخة المبنية منه.", 18],
  ["attribute / method", "Data stored in an object / a function belonging to it.", "خاصية / دالة تابعة للكائن.", 18],
  ["__init__ (constructor)", "Runs when an object is created; sets its attributes.", "الدالة البانية عند إنشاء الكائن.", 18],
  ["self", "The object a method is working on.", "الكائن الحالي.", 18],
  ["__str__", "Returns the text print() shows for an object.", "النص الذي يظهر عند طباعة الكائن.", 18],
  ["encapsulation", "Bundling data and methods and hiding internal details.", "التغليف: إخفاء التفاصيل الداخلية.", 18],
  ["inheritance / super()", "A child class reuses a parent / calls the parent's version.", "الوراثة / استدعاء نسخة الأب.", 19],
  ["overriding", "Redefining a parent method in a child class.", "إعادة تعريف دالة الأب في الابن.", 19],
  ["polymorphism", "Same method call, different behavior per class.", "تعدد الأشكال.", 19],
  ["composition", "An object containing other objects (has-a).", "كائن يحتوي كائنات أخرى.", 19],
  ["linear search", "Checking items one by one: O(n).", "البحث الخطي: فحص العناصر واحدًا واحدًا.", 22],
  ["binary search", "Halving a sorted list each step: O(log n).", "البحث الثنائي: تقسيم القائمة المرتبة نصفين.", 22],
  ["Big-O", "How the work grows as the data grows: O(1), O(log n), O(n), O(n²).", "طريقة وصف سرعة الخوارزمية مع زيادة البيانات.", 22],
  ["divide and conquer", "Split a problem, solve the parts, combine (e.g. merge sort).", "فرّق تسد: تقسيم المشكلة ثم دمج الحلول.", 22],
  ["numpy array", "A fast grid of numbers supporting whole-array math.", "مصفوفة أرقام سريعة.", 23],
  ["vectorization", "Applying an operation to a whole array without loops.", "تطبيق العملية على المصفوفة كاملة بدون حلقة.", 23],
  ["axis", "The direction of an operation: 0 = down rows, 1 = across columns.", "اتجاه العملية في المصفوفة.", 23],
  ["boolean mask", "An array of True/False used to filter another array.", "مصفوفة صح/خطأ للتصفية.", 23],
  ["machine learning", "Programs that learn patterns from examples instead of hand-written rules.", "تعلم الآلة: التعلم من الأمثلة بدل كتابة القواعد.", 24],
  ["feature / label", "An input measurement / the answer to predict.", "الخاصية / التصنيف المطلوب التنبؤ به.", 24],
  ["training / test set", "Data to learn from / unseen data to evaluate on.", "بيانات التدريب / بيانات الاختبار.", 24],
  ["classification / regression", "Predicting a category / predicting a number.", "التصنيف / التنبؤ بقيمة رقمية.", 24],
  ["k-NN", "Predicts by majority vote of the k closest training examples.", "خوارزمية أقرب الجيران.", 24],
  ["overfitting", "Memorizing training data and failing on new data.", "الحفظ بدل التعلم.", 24],
  ["accuracy / baseline", "Fraction of correct predictions / accuracy of always guessing the majority.", "الدقة / الدقة الأساسية للمقارنة.", 24],
  ["scikit-learn", "Python's main machine-learning library: fit, predict, score.", "مكتبة تعلم الآلة الأشهر في بايثون.", 25],
  ["decision tree", "A model made of learned if/else rules.", "شجرة القرار: قواعد if/else متعلَّمة.", 25],
  ["confusion matrix", "Table of true vs predicted classes.", "مصفوفة الالتباس: الحقيقي مقابل المتوقع.", 25],
  ["cross-validation", "Evaluating on several different splits and averaging.", "التحقق المتقاطع.", 25],
  ["linear regression", "Fits a straight line to predict a number.", "الانحدار الخطي.", 25],
  ["bag of words", "Representing text as word counts.", "تمثيل النص بعدد مرات ظهور الكلمات.", 26],
  ["TF-IDF", "Word counts weighted down for very common words.", "وزن الكلمات حسب أهميتها.", 26],
  ["Naive Bayes", "A fast probabilistic classifier, classic for spam and sentiment.", "مصنف احتمالي سريع.", 26],
  ["intent", "What a user wants from a message; used by chatbots.", "نية المستخدم.", 26],
  ["cosine similarity", "How similar two vectors' directions are (1 = same).", "تشابه الاتجاه بين متجهين.", 26],
  ["bias (in AI)", "Systematic unfairness learned from unrepresentative data.", "التحيز في الذكاء الاصطناعي.", 26],
  ["precision / recall", "Of those flagged, how many right / of real cases, how many found.", "الدقة النوعية / الاستدعاء.", 27],
  ["JSON", "A text format for saving dicts and lists: json.dump / json.load.", "صيغة نصية لحفظ القواميس والقوائم.", 30],
  ["closure", "A function that remembers variables from where it was created.", "دالة تتذكر المتغيرات من مكان إنشائها.", 26],
  ["stop words", "Very common words (the, how, do) often ignored in text AI.", "كلمات شائعة جدًا يتم تجاهلها في تحليل النصوص.", 30],
  ["capstone", "A final project that combines everything you learned.", "مشروع التخرج الذي يجمع كل ما تعلمته.", 29],
];
